export const title = "Представление";

// {
//   "_index": "gwar_2023_08_16",
//   "_type": "chelovek_predstavlenie",
//   "_id": "57618804",
//   "_score": 1,
//   "_source": {
//     "box_id": null,
//     "event_place": null,
//     "birth_date": null,
//     "birth_place_gubernia": null,
//     "document_author": null,
//     "military_unit_id": 2357,
//     "__type": "chelovek_predstavlenie",
//     "prikaz_date": null,
//     "rank": "генерал-майор",
//     "documents_pages": {
//       "documents_id": [
//         57504028
//       ],
//       "pages_id": [
//         130928602
//       ]
//     },
//     "id": 57618804,
//     "birth_place_volost": null,
//     "deal_id": 57501006,
//     "award_name": null,
//     "inventory_id": 396,
//     "document_date": "1915-01-10",
//     "award_num": null,
//     "birth_place": null,
//     "archive": "Российский Государственный Военно-исторический архив",
//     "shkaf_id": null,
//     "data_priziva": null,
//     "birth_place_id": null,
//     "inventory_num": "2",
//     "updated": "2018-12-25T15:04:01Z",
//     "prikaz_num": null,
//     "birth_place_np_type": null,
//     "deal": "О награждении орденами Св. Георгия и Георгиевским оружием по удостоению Думы, собирающейся при Штабе фронта",
//     "person_type": "Списки награжденных",
//     "fund_id": 344,
//     "box": null,
//     "doc_type": "Представления к награде",
//     "inventory": "Управление дежурного генерала",
//     "shkaf_name": null,
//     "document_name": "Переписка о представлении к награде за период 10.01.1915-21.12.1915 гг.",
//     "operations": null,
//     "birth_place_uezd": null,
//     "award_name_short": null,
//     "document_num": null,
//     "award_delivery_date": null,
//     "fund_num": "2048",
//     "operation_id": null,
//     "deal_num": "124",
//     "first_name": null,
//     "shkaf": null,
//     "birth_place_location": null,
//     "archive_short": "РГВИА",
//     "prikaz_author": null,
//     "last_name": "Шрейдер",
//     "middle_name": null,
//     "event_date_from": null,
//     "award_id": null,
//     "operation_name": null,
//     "event_date_to": null,
//     "fund": "Штаб главнокомандующего армиями Западного фронта",
//     "military_unit_name": "5-я стрелковая бригада",
//     "archive_id": 1
//   }
// }