name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION | ubuntu-duckarchive

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: '9'
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build

      - name: Run deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}/web/index.duckarchive.com
          EXCLUDE: ".git, .github, node_modules, .next"
          SCRIPT_AFTER: |
            PNPM_PATH=${{ secrets.DEPLOY_PATH }}/.local/share/pnpm/pnpm
            echo "PNPM_PATH: $PNPM_PATH"
            $PNPM_PATH install
            $PNPM_PATH run build
            echo "Deployed successfully"